Removing Coolpubsubclient, using orignal library
LeClubSandwichStudio/LaCOOLBoard pull request #190
Opened 2018-07-31 12:51 UTC by Kameeno

i removed the Coolpubsubclient, it was made because on Arduino environment is not able to define the flag `MQTT_MAX_PACKET_SIZE` on the fly at the compile time, now is defined inside the `platformio.ini`

2018-07-31 12:52 UTC, trap98 submitted a review, later dismissed

2018-08-08 15:32 UTC, 3rwww1 requested changes

2018-08-08 15:32 UTC, 3rwww1 commented on platformio.ini
> +  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY -DMQTT_MAX_PACKET_SIZE=3072"
Hmmm, why wouldn't we leave that to its original value in the source files you've just deleted (`4096`) ?

2018-08-08 15:32 UTC, 3rwww1 commented
Resolve conflicts please

2018-08-09 13:20 UTC, Kameeno commented on platformio.ini
> +  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY -DMQTT_MAX_PACKET_SIZE=3072"
was before do define a optimal size for us, i go to change it

2018-08-09 18:20 UTC, 3rwww1 approved these changes

2018-08-09 18:21 UTC, merged