Added support to SHT1X, pins 13 & 12
LeClubSandwichStudio/LaCOOLBoard pull request #90
Opened 2018-06-11 13:59 UTC by Kameeno

2018-06-12 20:24 UTC, 3rwww1 requested changes

2018-06-12 20:24 UTC, 3rwww1 commented on src/extras/CoolSHT1x.cpp
> +/**
Is that library anywhere on Github ?
If so, did you need to patch it ?
What does justify the need to copy-paste it here ?
I won't review anything more until you explain me those things.

2018-06-12 22:45 UTC, 3rwww1 commented on src/extras/CoolSHT1x.cpp
> +/**
OK, so as far as I can see, this library is [GPL v3](https://github.com/practicalarduino/SHT1x/blob/master/DISTRIBUTION)

There is absolutely NO WAY we are copy-pasting this code to **this** repository where the licence headers state we distribute the code here under the **MIT** license !

cc @simon-lacool

2018-06-18 14:37 UTC, 3rwww1 submitted a review, later dismissed

2018-06-19 09:42 UTC, LeSuedois requested changes
Sensor is working and code looks good.
Please add a example project in /examples/SHT1X and document that this sensor can't be used together with the jetpack.

2018-06-19 12:09 UTC, LeSuedois approved these changes

2018-06-19 12:10 UTC, merged